In [1]:
import torch

In [ ]:
vocab_size = 10000
context_size = 4
d_model = 6

In [ ]:
x = torch.LongTensor([[5542,1059, 572, 2]])

In [ ]:
position_embedding = torch.nn.Embedding(context_size, d_model)

In [ ]:
position_embedding.weight

Parameter containing:
tensor([[-0.2301, -1.7449, -0.3942,  1.1723, -0.2334, -2.0655],
        [ 0.2032, -0.8247,  0.2162,  0.3168, -0.5551, -0.6897],
        [-0.3452, -0.9355, -0.4812, -0.6397, -1.4076, -1.2537],
        [-1.5638, -1.3332,  0.4336, -0.1946, -1.3150,  0.5463]],
       requires_grad=True)

In [ ]:
position_embedding(torch.LongTensor([0]))

tensor([[-0.2301, -1.7449, -0.3942,  1.1723, -0.2334, -2.0655]],
       grad_fn=<EmbeddingBackward0>)

In [ ]:
positions = torch.arange(0, context_size).unsqueeze(0) ## 次元を追加
positions

tensor([[0, 1, 2, 3]])

In [ ]:
wpe = position_embedding(positions)
wpe

tensor([[[-0.2301, -1.7449, -0.3942,  1.1723, -0.2334, -2.0655],
         [ 0.2032, -0.8247,  0.2162,  0.3168, -0.5551, -0.6897],
         [-0.3452, -0.9355, -0.4812, -0.6397, -1.4076, -1.2537],
         [-1.5638, -1.3332,  0.4336, -0.1946, -1.3150,  0.5463]]],
       grad_fn=<EmbeddingBackward0>)

Embedding

In [9]:
# 埋め込みクラスのインスタンス化
token_embedding = torch.nn.Embedding(vocab_size, d_model)
token_embedding

Embedding(10000, 6)

In [ ]:
token_embedding.weight[:5]

tensor([[-0.5752, -0.5879,  0.2495, -0.8090,  1.1016, -0.1906],
        [ 0.4832,  0.4634, -1.3298,  0.8124, -0.9380, -0.4664],
        [-1.0674,  1.2012, -0.0125,  0.9528, -0.1569,  0.0928],
        [-0.0669,  0.8295,  1.0396,  0.9255,  0.6403,  1.3654],
        [ 0.1333,  1.2574,  0.8724,  0.2044, -0.2794, -0.0812]],
       grad_fn=<SliceBackward0>)

In [14]:
wte = token_embedding(x)

In [ ]:
wte + wpe

tensor([[[ 0.2450, -1.3478, -0.4895,  1.8310,  1.6156, -1.0105],
         [-0.1610,  0.1379,  0.0881, -0.9296, -1.7536,  0.9104],
         [ 1.1725,  0.0917,  0.5572, -1.1736, -0.6674, -1.6429],
         [-2.6312, -0.1320,  0.4211,  0.7582, -1.4719,  0.6391]]],
       grad_fn=<AddBackward0>)